modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/SilentChaos512/SilentGems/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/silents-gems"
#logoFile="examplemod.png" #optional
credits=""
authors="SilentChaos512"

[[mods]]
    modId="silentgems"
    version="${file.jarVersion}"
    displayName="Silent's Gems 3"
    updateJSONURL="https://raw.githubusercontent.com/SilentChaos512/SilentGems/1.14/update.json"
    description='''
    Downloads: https://www.curseforge.com/minecraft/mc-mods/silents-gems (I do not upload anywhere else)
    Changelog: https://github.com/SilentChaos512/SilentGems/blob/1.14/CHANGELOG.md
    Source: https://github.com/SilentChaos512/SilentGems/
    Issues: https://github.com/SilentChaos512/SilentGems/issues
    '''

[[dependencies.silentgems]]
    modId="forge"
    mandatory=true
    versionRange="[28.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.silentgems]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.silentgems]]
    modId="silentlib"
    mandatory=true
    versionRange="[4.4,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.silentgems]]
    modId="silentgear"
    mandatory=false
    versionRange="[1.3.11,)"
    ordering="AFTER"
    side="BOTH"